export const inputType = {
  input: "input",
  passwordinput:"passwordinput",
  select: "select",
  textarea: "textarea",
  checkbox: "checkbox",
  radio: "radio",
  date: "date",
  autocomplete: "autocomplete",
  switch: "switch",
  file: "file",
  number: "number",
  checkboxgroup: "checkboxgroup",
  simplefile: "simplefile",
  overviewfileinput: "overviewfileinput",
};
